# Generated by Django 2.1.8 on 2020-04-18 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('com_id', models.AutoField(primary_key=True, serialize=False, verbose_name='评论id')),
                ('com_content', models.CharField(max_length=500, verbose_name='评论内容')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('username', models.CharField(max_length=20, verbose_name='用户名称')),
                ('blog_id', models.IntegerField(verbose_name='博客id')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'db_table': 'comments',
            },
        ),
    ]
