# Generated by Django 2.1.8 on 2020-04-13 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('blog_id', models.AutoField(primary_key=True, serialize=False, verbose_name='博客id')),
                ('blog_title', models.CharField(max_length=50, verbose_name='博客标题')),
                ('author', models.CharField(max_length=20, verbose_name='作者')),
                ('content', models.TextField(max_length=5000, verbose_name='博客内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '博客',
                'verbose_name_plural': '博客',
                'db_table': 'blogs',
            },
        ),
    ]
